version: '3.8'

services:
   db:
      image: postgres:latest
      environment:
         - POSTGRES_DB=cicd-project
      env_file:
         - compose.env
      volumes:
         - pgdata:/var/lib/postgresql/data

   app:
      build:
         context: ./cicd-app
         dockerfile: Dockerfile
         tags:
            - cicd-project-back:0.1.0
      ports:
         - '3000:2022'
      depends_on:
         - db
      env_file:
         - compose.env

volumes:
   pgdata:
