version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - compose.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - compose.env

volumes:
  pgdata:
