name: CI with Docker
run-name: ${{ github.actor }} test une CI avec Docker
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: cicd-project
          POSTGRES_USER: ${{ secrets.CITY_API_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.CITY_API_DB_PWD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./cicd-app

      - name: Add data
        run: node script.js
        working-directory: ./cicd-app
        env:
          DATABASE_URL: postgres://${{ secrets.CITY_API_DB_USER }}:${{ secrets.CITY_API_DB_PWD }}@localhost:5432/cicd-project

      - name: Run tests
        run: npm test
        working-directory: ./cicd-app
        env:
          CITY_API_DB_URL: postgres://${{ secrets.CITY_API_DB_USER }}:${{ secrets.CITY_API_DB_PWD }}@localhost:5432/cicd-project
