name: CI with Docker
run-name: ${{ github.actor }} test une CI avec Docker
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d
        env:
          CITY_API_DB_USER: ${{ secrets.CITY_API_DB_USER }}
          CITY_API_DB_PWD: ${{ secrets.CITY_API_DB_PWD }}

      - name: Shutdown Docker Compose
        run: docker-compose down
